name: Deploy NestJS Docker App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: SSH deploy to server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            docker pull sony2k20/nestjs-email-service:latest
            docker stop nestjs-email-service || true
            docker rm nestjs-email-service || true
            docker run -d \
              --name nestjs-email-service \
              -p 3000 \
              -e SMTP_HOST=${{ secrets.SMTP_HOST }} \
              -e SMTP_PORT=${{ secrets.SMTP_PORT }} \
              -e SMTP_USER=${{ secrets.SMTP_USER }} \
              -e SMTP_PASS=${{ secrets.SMTP_PASS }} \
              sony2k20/nestjs-email-service:latest
