name: Deploy NestJS Docker App to Prod

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH deploy to server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            docker stop ${{ github.event.repository.name }} || true
            docker rm ${{ github.event.repository.name }} || true
            docker pull sony2k20/${{ github.event.repository.name }}:latest
            docker run -d \
              --name ${{ github.event.repository.name }} \
              --network my_network \
              --restart unless-stopped \
              -p 3000:3000 \
              -e NODE_ENV="prod" \
              -e SMTP_HOST=${{ secrets.SMTP_HOST }} \
              -e SMTP_PORT=${{ secrets.SMTP_PORT }} \
              -e SMTP_USER=${{ secrets.SMTP_USER }} \
              -e SMTP_PASS=${{ secrets.SMTP_PASS }} \
              -e MONGODB_URI=${{ secrets.MONGODB_URI }} \
              sony2k20/${{ github.event.repository.name }}:latest
