name: Build NestJS App and Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      # - name: Install dependencies
      #   run: |
      #     npm ci --legacy-peer-deps

      #   - name: Run tests
      #     run: |
      #       npm run test -- --watch=false --bail --max-workers=2

      # - name: Build application
      #   run: |
      #     npm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create service account key file
        run: |
          echo "${{ secrets.FIRESTORE_KEY_FILE }}" > service-account-firestore.json
        shell: bash

      - name: Build Docker image
        run: |
          docker buildx build \
          --platform linux/arm64,linux/amd64 \
          --tag sony2k20/${{ github.event.repository.name }}:latest \
          --build-arg FIRESTORE_SERVICE_ACCOUNT_KEY="$(cat service-account-firestore.json)" \
          --push .

  update-deployment:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout the source repo
        uses: actions/checkout@v3

      - name: Clone Target Repository
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git config --global credential.helper cache
          git clone https://${{ secrets.COMMIT_TO_REPO_TOKEN }}@github.com/Sony2k20/gitops-deployments.git target-repo
          cd target-repo

      - name: Generate Timestamp
        id: generate-timestamp
        run: echo "timestamp=$(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

      - name: Update Deployment YAML with Timestamp
        run: |
          cd target-repo
          sed -i "/deploymentTime:/s/:.*/: \"$(date "+%Y-%m-%d %H:%M:%S")\"/" helm-charts/${{ github.event.repository.name }}/templates/deployment.yaml

      - name: Commit and Push Changes
        run: |
          cd target-repo
          git add helm-charts/${{ github.event.repository.name }}/templates/deployment.yaml
          git commit -m "Update deployment timestamp to $timestamp"
          git push origin master
